CUDA_VISIBLE_DEVICES=0   python main.py \
--gpu 1 \
--dataroot '/export/home/dv/dv029/DFL-CNN/dataset' \
--result './vis_result' \
--lr 0.005 \
--epochs 40 \
--workers 4 \
--train_batchsize_per_gpu 8 \
--init_type 'xavier' \
--print-freq 1 \
--vis_epoch 1 \
--num_filters 4
