CUDA_VISIBLE_DEVICES=0   python main.py \
--gpu 1 \
--dataroot '/export/home/dv/dv029/DFL-CNN/dataset' \
--result './vis_result' \
--lr 0.05 \
--epochs 40 \
--workers 8 \
--train_batchsize_per_gpu 16 \
--init_type 'normal' \
--print-freq 100 \
--eval_epoch_threshold 20